<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="bunit" />
		<PackageReference Include="coverlet.collector">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="NUnit" />
		<PackageReference Include="NUnit.Analyzers">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NUnit3TestAdapter" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="SsidArqNet.InternalComponents.Blazor.TemplateBuilder" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Reporta.Templates.GAT_SSID.SsidArqNet.ReporteSimple\Reporta.Templates.GAT_SSID.SsidArqNet.ReporteSimple.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="NUnit.Framework" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="PlantillaEjemplo\LLamadaConversorPrueba.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Import Project="../../Project.Build.targets" />

</Project>
