<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="CertificadoProvisional.Example.json" />
		<Content Remove="CertificadoProvisional.Example.eu.json" />
		<None Include="CertificadoProvisional.Example.json" />
		<None Include="CertificadoProvisional.Example.eu.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" />
		<PackageReference Include="SsidArqNet.Components.Blazor.Reporta" />
	</ItemGroup>

	<PropertyGroup>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>Compilados</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Compilados\**" />
		<Content Remove="Compilados\**" />
		<EmbeddedResource Remove="Compilados\**" />
		<None Remove="Compilados\**" />
	</ItemGroup>

	<Import Project="../../Project.Build.targets" />

</Project>
